# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'youtube-upload' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for youtube-upload
pod 'Alamofire'
pod 'SwiftyJSON' 
pod 'GoogleSignIn'
  target 'youtube-uploadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'youtube-uploadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
